
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdYZqaZ8tXIhBvyRNkzaUWb4Mn50dLtE',
    appId: '1:464200726815:web:d69ce8a952eb1e91d0d82a',
    messagingSenderId: '464200726815',
    projectId: 'hikenity',
    authDomain: 'hikenity.firebaseapp.com',
    storageBucket: 'hikenity.appspot.com',
    measurementId: 'G-N300YNR714',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5V7vHvZuIEBKJHszjC_qA04zGfhuEvfE',
    appId: '1:464200726815:android:2ebd747d46bbf2e2d0d82a',
    messagingSenderId: '464200726815',
    projectId: 'hikenity',
    storageBucket: 'hikenity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxy8a5MCmFoyI_2yhDSnpVEvFoOGUPfzw',
    appId: '1:464200726815:ios:3ad61b2e5182d4bed0d82a',
    messagingSenderId: '464200726815',
    projectId: 'hikenity',
    storageBucket: 'hikenity.appspot.com',
    iosBundleId: 'com.example.hikenityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxy8a5MCmFoyI_2yhDSnpVEvFoOGUPfzw',
    appId: '1:464200726815:ios:3ad61b2e5182d4bed0d82a',
    messagingSenderId: '464200726815',
    projectId: 'hikenity',
    storageBucket: 'hikenity.appspot.com',
    iosBundleId: 'com.example.hikenityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZdYZqaZ8tXIhBvyRNkzaUWb4Mn50dLtE',
    appId: '1:464200726815:web:26d5dd6e70e1f09ed0d82a',
    messagingSenderId: '464200726815',
    projectId: 'hikenity',
    authDomain: 'hikenity.firebaseapp.com',
    storageBucket: 'hikenity.appspot.com',
    measurementId: 'G-1E58F622P1',
  );
}
